version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.4-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 10s
      retries: 6
      start_period: 5s
    restart: always

  config-server:
    image: vincennlin/flashcardweb-config-server
    environment:
      - spring.rabbitmq.host=rabbitmq
    ports:
      - "8888:8888"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: always

  discovery-service:
    image: vincennlin/flashcardweb-discovery-service
    environment:
      - spring.profiles.active=prod
      - spring.rabbitmq.host=rabbitmq
      - config.server.ip=config-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 15s
    restart: always

  user-service:
    image: vincennlin/flashcardweb-user-service
    environment:
      - spring.profiles.active=prod
      - config.server.ip=config-server
      - spring.rabbitmq.host=rabbitmq
      - eureka.server.ip=discovery-service
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 30s
    restart: always

  note-service:
    image: vincennlin/flashcardweb-note-service
    environment:
      - spring.profiles.active=prod
      - config.server.ip=config-server
      - spring.rabbitmq.host=rabbitmq
      - eureka.server.ip=discovery-service
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 30s
    restart: always

  flashcard-service:
    image: vincennlin/flashcardweb-flashcard-service
    environment:
      - spring.profiles.active=prod
      - config.server.ip=config-server
      - spring.rabbitmq.host=rabbitmq
      - eureka.server.ip=discovery-service
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 30s
    restart: always

  ai-service:
    image: vincennlin/flashcardweb-ai-service
    environment:
      - spring.profiles.active=prod
      - config.server.ip=config-server
      - spring.rabbitmq.host=rabbitmq
      - eureka.server.ip=discovery-service
    ports:
      - "8084:8084"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8084/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 30s
    restart: always

  api-gateway:
    image: vincennlin/flashcardweb-api-gateway
    environment:
      - spring.profiles.active=prod
      - config.server.ip=config-server
      - spring.rabbitmq.host=rabbitmq
      - eureka.server.ip=discovery-service
    ports:
      - "8765:8765"
    depends_on:
      user-service:
        condition: service_healthy
      note-service:
        condition: service_healthy
      flashcard-service:
        condition: service_healthy
      ai-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8765/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 30s
    restart: always
