name: Build and Push Docker Images for Flashcardweb Microservices

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build and push config-server
      - name: Build config-server with Maven
        run: mvn -B package --file config-server/pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for config-server
        id: meta-config-server
        uses: docker/metadata-action@v3
        with:
          images: |
            flashcardweb-config-server

      - name: Build and push Docker image for config-server
        id: push-config-server
        uses: docker/build-push-action@v3
        with:
          context: config-server
          push: true
          tags: vincennlin/flashcardweb-config-server:latest
          labels: ${{ steps.meta-config-server.outputs.labels }}

      # Build and push discovery-service
      - name: Build discovery-service with Maven
        run: mvn -B package --file discovery-service/pom.xml

      - name: Extract metadata for discovery-service
        id: meta-discovery-service
        uses: docker/metadata-action@v3
        with:
          images: |
            flashcardweb-discovery-service

      - name: Build and push Docker image for discovery-service
        id: push-discovery-service
        uses: docker/build-push-action@v3
        with:
          context: discovery-service
          push: true
          tags: vincennlin/flashcardweb-discovery-service:latest
          labels: ${{ steps.meta-discovery-service.outputs.labels }}

      # Build and push user-service
      - name: Build user-service with Maven
        run: mvn -B package --file user-service/pom.xml

      - name: Extract metadata for user-service
        id: meta-user-service
        uses: docker/metadata-action@v3
        with:
          images: |
            flashcardweb-user-service

      - name: Build and push Docker image for user-service
        id: push-user-service
        uses: docker/build-push-action@v3
        with:
          context: user-service
          push: true
          tags: vincennlin/flashcardweb-user-service:latest
          labels: ${{ steps.meta-user-service.outputs.labels }}

      # Build and push note-service
      - name: Build note-service with Maven
        run: mvn -B package --file note-service/pom.xml

      - name: Extract metadata for note-service
        id: meta-note-service
        uses: docker/metadata-action@v3
        with:
          images: |
            flashcardweb-note-service

      - name: Build and push Docker image for note-service
        id: push-note-service
        uses: docker/build-push-action@v3
        with:
          context: note-service
          push: true
          tags: vincennlin/flashcardweb-note-service:latest
          labels: ${{ steps.meta-note-service.outputs.labels }}

      # Build and push flashcard-service
      - name: Build flashcard-service with Maven
        run: mvn -B package -DskipTests --file flashcard-service/pom.xml

      - name: Extract metadata for flashcard-service
        id: meta-flashcard-service
        uses: docker/metadata-action@v3
        with:
          images: |
            flashcardweb-flashcard-service

      - name: Build and push Docker image for flashcard-service
        id: push-flashcard-service
        uses: docker/build-push-action@v3
        with:
          context: flashcard-service
          push: true
          tags: vincennlin/flashcardweb-flashcard-service:latest
          labels: ${{ steps.meta-flashcard-service.outputs.labels }}

      # Build and push ai-service
      - name: Build ai-service with Maven
        run: mvn -B package --file ai-service/pom.xml

      - name: Extract metadata for ai-service
        id: meta-ai-service
        uses: docker/metadata-action@v3
        with:
          images: |
            flashcardweb-ai-service

      - name: Build and push Docker image for ai-service
        id: push-ai-service
        uses: docker/build-push-action@v3
        with:
          context: ai-service
          push: true
          tags: vincennlin/flashcardweb-ai-service:latest
          labels: ${{ steps.meta-ai-service.outputs.labels }}

      # Build and push api-gateway
      - name: Build api-gateway with Maven
        run: mvn -B package --file api-gateway/pom.xml

      - name: Extract metadata for api-gateway
        id: meta-api-gateway
        uses: docker/metadata-action@v3
        with:
          images: |
            flashcardweb-api-gateway

      - name: Build and push Docker image for api-gateway
        id: push-api-gateway
        uses: docker/build-push-action@v3
        with:
          context: api-gateway
          push: true
          tags: vincennlin/flashcardweb-api-gateway:latest
          labels: ${{ steps.meta-api-gateway.outputs.labels }}
